# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:ios)

platform :ios do
 desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "NavigatorApp.xcodeproj")
    build_app(workspace: "NavigatorApp.xcworkspace", scheme: "NavigatorApp",xcargs: "-allowProvisioningUpdates")
    upload_to_testflight(api_key: {
      key_id: ENV['APPLE_KEY_ID'],
      issuer_id: ENV['ISSUER_ID'],
      key_filepath: "./ios/AuthKey.p8"
    }, provisioning_profile: 'ios/profile.mobileprovision')
    slack(message: "Successfully distributed a new beta build")
  end
end